### ISSUE TITLE
加入扫描小程序列表功能

### ISSUE THREAD

**Issue by moyuwa** [biggerstar/wedecode#1]
作者看一下这个项目
https://github.com/wux1an/wxapkg
能把它的小程序扫描功能加入吗？

**Comment by biggerstar** [comment]
这是一个有用的功能，我找个时间加上

**Comment by moyuwa** [comment]
它那个工具下载的app名字json解析老是出差，希望修复一下

**Comment by biggerstar** [comment]
小程序包扫描功能已在 `v0.6.0` 版本中支持
