### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hfx96** [biggerstar/wedecode#2]
您好，请问在编译完成后，会出现这样的报错，但是也编译完成了，这样的话是什么原因导致的，会不会产生编译不完整的情况。
<img width="1165" alt="image" src="https://github.com/biggerstar/wedecode/assets/65392776/0e7bc13a-619b-4183-8a27-4941c9ad8c3c">

**Comment by biggerstar** [comment]
你能发个项目地址进行复现吗， 我找找问题进行修复

**Comment by mzc9915** [comment]
<img width="798" alt="image" src="https://github.com/biggerstar/wedecode/assets/50267789/a41c63e3-0bc7-4110-99d4-d57a2a6c6bbf">
也是遇到同样的问题，目前 node 16 和 node 20 都尝试了。 小程序包我放在 下面链接中。
链接: https://pan.baidu.com/s/1njEHElsE2DZmucJfmRZTZQ 提取码: rcdw。

**Comment by biggerstar** [comment]
该问题目前已经在 `v0.2.7` 版本中修复
你提供的包中使用反编译目前还存在些许问题， 其中vue的路由无法正确导航到 home 页面， 
你可以直接在 `app.json` 的 `entryPagePath` 修改入口重定向到任何组件， 比如入口则可以设置成 `pages/index/home`

**Comment by hfx96** [comment]
> 该问题目前已经在 `v0.2.7` 版本中修复 你提供的包中使用反编译目前还存在些许问题， 其中vue的路由无法正确导航到 home 页面， 你可以直接在 `app.json` 的 `entryPagePath` 修改入口重定向到任何组件， 比如入口则可以设置成 `pages/index/home`

Thanks so much
