### ISSUE TITLE
反编译后app.json出错

### ISSUE THREAD

**Issue by JXDYYY** [biggerstar/wedecode#4]
反编译app.json当中的"tabBar"中的
"\"会被替换成"//"，不知道是我自己的问题还是什么
![58b0f2c6-0f16-4749-99b2-f0d3cf5c108a](https://github.com/biggerstar/wedecode/assets/102240507/61b81adb-8267-4c5d-b03d-e400571e5a0c)

**Comment by biggerstar** [comment]
你是用的是 window 还是 mac

**Comment by biggerstar** [comment]
另外您如果能提供小程序的包更好，  正常这个路径无关使用什么系统的， 出现这个原因有可能小程序包在反编译的时候有些细节没处理好
