### ISSUE TITLE
npm i wedecode -g 报错

### ISSUE THREAD

**Issue by 13271473920** [biggerstar/wedecode#6]
npm warn deprecated npx@10.2.2: This package is now part of the npm CLI.
npm warn deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.

你遇到的这两个警告信息分别指向了两个不同的问题：

npx 被弃用并集成到 npm CLI:

警告信息 npm warn deprecated npx@10.2.2: This package is now part of the npm CLI. 表示 npx 这个包已经不再作为一个独立的包存在，而是被集成到了 npm 的命令行界面（CLI）中。npx 最初是一个独立的包，用于运行项目中的包或者安装的全局包，现在你可以直接使用 npm exec 或 npm run 命令来达到相同的效果。
vm2 库存在严重安全问题并已停止维护:

警告信息 npm warn deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm. 指出 vm2 这个库包含了关键的安全问题，不应该在生产环境中使用，并且该项目的维护已经停止。这意味着任何使用 vm2 的项目都面临着潜在的安全风险，并且可能在未来遇到兼容性问题，因为没有新的更新来修复bug或添加新特性。

该警告建议迁移到 isolated-vm，这是一个替代库，提供了与 vm2 类似的功能，但更加安全，并且仍在维护中。

如果你的项目依赖了这些包，你应该采取以下步骤：

对于 npx，检查你的项目中是否有使用 npx 的地方，如果有，考虑替换为 npm exec 或 npm run。
对于 vm2，你应该立即评估你的项目，寻找替代方案，比如 isolated-vm，并计划迁移你的代码库以避免安全风险。
在处理这些警告时，确保你理解了依赖的包在你的项目中的作用，并评估替代方案的可行性和兼容性。如果你不确定如何进行，可以寻求社区的帮助或咨询专业的开发人员。

**Comment by biggerstar** [comment]
这两个只是警告信息， 不会影响正常使用的， 直接忽略就行了
